//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wechat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yamahainfo
    {
        public int id { get; set; }
        public string openid { get; set; }
        public string wenti { get; set; }
        public string daan { get; set; }
        public string zqdaan { get; set; }
        public string shif { get; set; }
        public Nullable<System.DateTime> wtime { get; set; }
    }
}
